### ISSUE TITLE
Coverage is determined by MAX block count

### ISSUE THREAD

**Issue by hacksysteam** [pyoor/distiller#2]
Hi @pyoor 

I see that the coverage is being determined the max block count in minimize.py.

What I believe is this is not the very right way to do it, let me know if I'm wrong. Let's consider a scenario:

1.

```
for (i=0; i<100; i++) {
     printf('Yey');
}
```

2.

```
for (i=0; i<10; i++) {
     printf('Yey');
}
```

So, suppose there are two files that exercise this for loop but first files does 100 iteration and second file does 10 iteration.

I believe that minimizer will pick the 1st file as it exercises the same path but for 100 iteration, where as it should select 2nd file.

Do you agree on it?

Thanks.

**Comment by pyoor** [comment]
It does neither.  During the preprocessing, which occurs as traces are stored in the DB, we uniq the list of basic blocks prior to insertion.  We do not track the number of iterations a specific block executes.

Minimization the iterates of traces from greatest to least total block count.  The seed that introduces a basic block with the greatest size will eventually be included in the final minset.  This is a simple way of reducing the size of the final minset while still covering all unique blocks.

**Comment by hacksysteam** [comment]
Awesome. Thanks for explaining. I'll close this ticket. Cheers.
