### ISSUE TITLE
Add support to pass program arguments to trace_runner.py

### ISSUE THREAD

**Issue by hacksysteam** [pyoor/distiller#4]
Currently `distiller` does not have any option to pass additional arguments to the program being instrumented.

**Comment by pyoor** [comment]
Do you mean command line arguments for the instrumented binary?

**Comment by hacksysteam** [comment]
Yes

**Comment by pyoor** [comment]
Fixed issue with commit f0a4fa526065401f6cfed153fb6c2059be8bb8da
